# Generated by Django 2.2.3 on 2020-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpictures',
            name='image',
            field=models.ImageField(upload_to='user_images/'),
        ),
    ]
